services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
      tags:
        - downloader-bot-dev:latest
    volumes:
      # Adds current directory as volume.
      - .:/bot/
    env_file:
      - .env
    depends_on:
      azurite:
        condition: service_started
      azurite_init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "discordhealthcheck" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/bot/
    command: [ "python", "-m", "taskiq", "worker", "--reload", "--reload-dir", "/bot", "--log-level=INFO", "downloader_bot.tq:broker", "downloader_bot.tasks" ]
    environment:
      - TASKIQ_PROCESS_ROLE=worker
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "python", "-m", "downloader_bot.worker.healthcheck" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/bot/
    command: [ "python", "-m", "taskiq", "scheduler", "--log-level=INFO", "downloader_bot.tq:scheduler", "downloader_bot.tasks" ]
    environment:
      - TASKIQ_PROCESS_ROLE=scheduler
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "python", "-m", "downloader_bot.worker.healthcheck" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  taskiq_admin:
    image: ghcr.io/taskiq-python/taskiq-admin:latest
    container_name: taskiq_admin
    ports:
      - 3000:3000
    environment:
      TASKIQ_ADMIN_API_TOKEN: ${TASKIQ_ADMIN_API_TOKEN:?}
    volumes:
      - admin_data:/usr/database/

  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    restart: always
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  rabbitmq:
    image: rabbitmq:4.3.0-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:?}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:?}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    healthcheck:
      # use the flag --erlang-cookie if setting the erlang
      # cookie was necessary (comment by red-riding-hood)
      # test: rabbitmq-diagnostics -q ping --erlang-cookie "mycookie"
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 60s

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 1s
      retries: 30

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.35.0
    container_name: "azurite"
    hostname: azurite
    restart: always
    # skipApiVersionCheck - https://github.com/Azure/Azurite/discussions/2627
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --skipApiVersionCheck"
    ports:
      - "10000:10000"
      # required, see https://github.com/Azure/Azurite/issues/1666
    healthcheck:
      test: nc 127.0.0.1 10000 -z
      interval: 1s
      retries: 30

  # https://github.com/Azure/Azurite/issues/1665#issuecomment-1236796659
  azurite_init:
    image: mcr.microsoft.com/azure-cli:latest
    command:
      - /bin/sh
      - -c
      - |
        az storage container create --name media
    depends_on:
      azurite:
        condition: service_healthy
    environment:
      # https://github.com/Azure/Azurite/blob/main/README.md#usage-with-azure-storage-sdks-or-tools
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;

volumes:
  redis-data:
  postgres-data:
  rabbitmq_data:
  rabbitmq_log:
  admin_data:
